### ISSUE TITLE
[Picker Input] Value changes it’s position in the list after switching the ‘show only selected’ toggle

### ISSUE THREAD

**Issue by mari-shakhanava** [epam/UUI#1032] opened 2023-02-09 12:56 UTC
## Steps to Reproduce

1) Open picker input list (with Lazy DataSource)
2) Click on [select all] button 
3) Unselect any item from the top of the list 
4) Select it again 
5) Turn on the ‘show only selected’ toggle

## Actual result
Particular item goes to the end of the list
![2023-02-09_13h45_44](https://user-images.githubusercontent.com/70166849/217818391-aa812ab4-3177-4553-b75f-dc0105921100.gif)

## Expected result

Item should not change position 

## Environment
* UUI version: 4.10.0
* Browser name: Chrome
* Operating System: Windows

**Comment by AlekseyManetov** [comment] 2023-02-13 16:58
Duplicate of #683

**Closed by AlekseyManetov** 2023-02-13 16:58 UTC
Labels: bug
