### ISSUE TITLE
[PickerInput] Weird behavior while using with modals

### ISSUE THREAD

**Issue by shushenchik** [epam/UUI#882] opened 2022-12-19 12:25 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description

We want to perform some asynchronous actions on the `PickerInput` component's value change. For example, we want to show the user a modal with a warning message. But some unexpected bugs occur. Actually, it feels like the `PickerInput` component has its own internal state.

Here is a little [demo](https://codesandbox.io/s/uui-forked-4c4l28?file=/Example.tsx).

## Bug 1

Steps to reproduce:

1. Pass an empty (like `noop`) `onValueChange` handler to the `PickerInput` component. 
2. Select any value.

Expected result: Value is not changed.

Actual result: Clicked value is selected. If you click on another value, then the selected value will be *switched*.

![BUG_1](https://user-images.githubusercontent.com/74292110/208424909-2e86f58a-3186-4e85-bec8-37194c27565f.gif)

## Bug 2

Steps to reproduce:

1. Clear any value by clicking the cross icon on its label.
2. Click the "Cancel" button in the opened modal.
3. Click the cross icon of the same value again.

Expected result: Modal appears again.

Actual result: Nothing happens. Modal appears only after the second click.

![BUG_2](https://user-images.githubusercontent.com/74292110/208425040-493e5bc2-cdbf-443a-a431-13ad2d18d104.gif)

## Bug 3

Steps to reproduce:

1. Select some values.
2. Clear all values by clicking the cross icon.
3. Click the "Cancel" button in the opened modal.
4. Open the `PickerInput` component's dropdown.
5. DO NOT hover on data rows!
6. Switch the "Show only selected" toggle. **=> "No result found" message is shown.**
7. Switch the "Show only selected" toggle back.
8. NOW hover on data rows!
9. Switch the "Show only selected" toggle one more time. **=> Selected values are back.**

![BUG_3](https://user-images.githubusercontent.com/74292110/208425331-00f89776-5e1f-4e8b-a2df-7f5d3505186d.gif)

## Bug 4 (bonus)

Couldn't reproduce in the sandbox. Here is a gif:

![BUG_4](https://user-images.githubusercontent.com/74292110/208425387-63fd9f96-a1f6-44ff-8435-569970960c3b.gif)

As you can see, instead of removing a value it duplicates. We suppose it might be a related issue.

## Environment

* UUI version: 4.8.5
* Browser name: Chrome 108
* Operating System: Windows 10

**Comment by Kunzetsov** [comment] 2023-01-10 12:45
@shushenchik, I'm sorry, unfortunately, I can't reproduce `BUG 2` on your sandbox demo. Could you, please, recheck if it is still present? Thanks a lot 😃 
 
https://user-images.githubusercontent.com/22456368/211554670-d6ce5844-3974-45a6-94a4-9bcf99105c07.mov

**Comment by Kunzetsov** [comment] 2023-01-10 13:53
`Bug 3` was fixed by https://github.com/epam/UUI/pull/930.

https://user-images.githubusercontent.com/22456368/211569288-7ac0add7-b88d-415b-b1f9-7aad7e8b7182.mov

**Comment by AlekseyManetov** [comment] 2023-01-11 14:35
Will be fixed in next release

**Closed by AlekseyManetov** 2023-01-11 14:35 UTC
Labels: bug
