### ISSUE TITLE
[PickeInput]: clear doesn't work with array empty value

### ISSUE THREAD

**Issue by JuliaMV** [epam/UUI#2477] opened 2024-08-23 06:42 UTC
## Steps to Reproduce

1. Create a PickerInput with emptyValue=[] or open [sandbox](https://codesandbox.io/p/sandbox/uui-forked-xm9whs?file=%2FExample.tsx)
2. Select all items by clicking "select all" button in dropdown footer.
3. Clear all items by clicking cross button in picker toogler.

## Actual result

Cross button in picker toogler is displayed. 
Clear all button in dropdown footer is displayed.

## Expected result

Cross and clear all buttons aren't visible

## Environment

* UUI version: 5.9.0 electric
* Browser name: Chrome
* Operating System: Win

**Comment by NatalliaAlieva** [comment] 2024-08-26 08:59
Duplicate of [this](https://github.com/epam/UUI/issues/2472) ticket.

**Closed by NatalliaAlieva** 2024-08-26 08:59 UTC
Labels: bug
