### ISSUE TITLE
[RTE]: Numeric/bullet to checkbox list conversion

### ISSUE THREAD

**Issue by cpof-tea** [epam/UUI#1855] opened 2023-12-15 14:00 UTC
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Description

Checkbox list can be converted to bullet/numeric list, but bullet/numeric list can't be converted to checkbox list.

## Steps to Reproduce

Open RTE (for example, [here](https://uui.epam.com/documents?id=richTextEditor&mode=doc&isSkin=null&category=components))

1. Create numeric/bullet list with some items
2. Click checkbox list

## Actual result

List stays as is

## Expected result

List converted to checkbox

## Environment

* UUI version: 5.4.2
* Browser name: FF 120.0
* Operating System: Ubuntu 20.04

**Comment by NatalliaAlieva** [comment] 2023-12-18 08:57
This ticket is a duplicate of case №15 in the ticket [[RTE]: known issues with RTE (after its update)](https://github.com/epam/UUI/issues/1422).

**Closed by NatalliaAlieva** 2023-12-18 08:57 UTC
Labels: bug, RTE

**Comment by cpof-tea** [comment] 2024-01-03 11:53
@NatalliaAlieva why you've marked as "not planned"?

**Comment by NatalliaAlieva** [comment] 2024-01-03 12:00
Hello @cpof-tea!
Because it is planned as part of another ticket.
