### ISSUE TITLE
Columns overlap on adjustment

### ISSUE THREAD

**Issue by stanislavec** [epam/UUI#1389] opened 2023-05-31 21:41 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description
Column overlaps next one during ajustment

## Steps to Reproduce

1. Open [docs](https://uui.epam.com/documents?id=tablesOverview&mode=doc&skin=UUI4_promo&category=tables#column_size_and_content_align_configuration)
2. Set Name & Title columns as first after checkbox 
3. Try to adjust Name column

Check video below.

## Actual result

Data overlaps next cell content. Problem is visible on docs page, but in our project problem is the same.

[UUI_table_adjustment.webm](https://github.com/epam/UUI/assets/34837948/66f9df5e-c976-4ef4-b873-4282b9a07f86)

## Expected result

`text-ellipsis` or `overflow` rule hides column content to avoid overlap. Or something like that. 

## Environment

* UUI version: 4.10.2
* Browser name: Chrome
* Operating System: MacOS, Windows

**Comment by AlekseyManetov** [comment] 2023-06-02 08:15
duplicate of https://github.com/epam/UUI/issues/1163, will be fixed in future release

**Closed by AlekseyManetov** 2023-06-02 08:15 UTC
Labels: bug
