### ISSUE TITLE
[Drag & Drop]:  Drag and drop is processed as a click so section expand/collapse when dragging

### ISSUE THREAD

**Issue by OlegKryvokobylskyi** [epam/UUI#1435] opened 2023-06-26 11:33 UTC
## Description

When the user moves (drags) a closed section, it opens and closes if the section is open.
## Steps to Reproduce

1. Open [www.uui.epam.com](https://uui.epam.com/)
3. Click on the "Demo" tab in the header
4. Click on the Drug & Drop area
5. Move(drug) opened "Section # 1"

## Actual result
"Section #1" closes unexpectedly

## Expected result
Drag and drop should not be processed as a click so "Section #1"  should just drug and not close.

## Environment

* UUI version: 5.0.1
* Browser name: any
* Operating System: any

**Comment by dimaanj** [comment] 2023-10-26 09:29
Can't reproduce it any more. @OlegKryvokobylskyi Could you please check it one more time and share a video if it's reproduces still?

**Comment by OlegKryvokobylskyi** [comment] 2023-10-26 10:28
@dimaanj Still able to reproduce, please see video attached:

https://github.com/epam/UUI/assets/129292145/8be1d6ea-3fb9-47d8-9477-ae48366b8936

**Comment by dimaanj** [comment] 2023-10-31 08:25
We have reduced the draggable area to the dot button.

**Comment by NatalliaAlieva** [comment] 2023-11-22 11:10
Released in 5.4.0 version.

**Closed by NatalliaAlieva** 2023-11-22 11:10 UTC
Labels: bug
