### ISSUE TITLE
[DatePicker] Dates don’t match week days when week in the calendar starts from Sunday

### ISSUE THREAD

**Issue by MarharytaBykava** [epam/UUI#893] opened 2022-12-21 13:59 UTC
## Description
Dates don’t match week days when week in the calendar starts from Sunday

## Steps to Reproduce
User has calendar in their system that starts from Sunday.

1. Open the date picker.

## Actual result

The week starts from Sunday but the dates start from Monday. The issue disappears after page reload.  
<img width="1076" alt="date_picker_issue" src="https://user-images.githubusercontent.com/87802989/208920551-4f998858-b876-4ab0-9342-dc88c0e969f7.png">

## Expected result

The week starts from Sunday and the dates match the week day.

## Environment

* UUI version: 4.8.2
* Browser name: Chrome
* Operating System: Win 10 pro

**Comment by MarharytaBykava** [comment] 2023-01-09 06:48
Hi, @Sushasgit!
Actually we changed the locale in one place to translate some words from date picker into Russian. Here is this line:
`i18n.datePicker.locale = locale === 'en-US' ? 'en-in' : 'ru';`
Unfortunately, I can’t reproduce the issue in codesendbox. It was found by our end user on the production environment and we also didn’t manage to catch it.

**Comment by Sushasgit** [comment] 2023-01-27 15:40
Hi, @MarharytaBykava we've checked this issue and we still couldn't reproduce it. This could be related to localisation. According to docs this import is required:
https://uui.epam.com/documents?id=datePicker&mode=doc&skin=UUI4_promo&category=components
<img width="1060" alt="Screenshot at Jan 27 17-32-58" src="https://user-images.githubusercontent.com/26334961/215125830-b8f1d8ac-fba1-4190-9d39-b16168d431fd.png">
We've checked without such import and this can cause issue with translation and weeks matching.

All others case if import exist is working fine. We'll close the issue for now, but if you catch such issue again please let us know.

**Closed** 2023-01-29 20:34 UTC
Labels: bug

**Comment by MarharytaBykava** [comment] 2023-02-07 09:49
Hi, @Sushasgit, thank you for answer!
