### ISSUE TITLE
[DataTable] [ColumnsConfigurationModal] setting column visible does not consistently put column on last place

### ISSUE THREAD

**Issue by Kernstall** [epam/UUI#1471] opened 2023-07-06 14:04 UTC
## Description
sometimes newly checked columns in ColumnsConfigurationModal appear in wrong order, as they are supposed to be last among selected columns.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open ColumnsConfigurationModal 
2. Check hidden columns to be visible

## Actual result

[REXP Digital Platform.webm](https://github.com/epam/UUI/assets/16035287/656693c5-b441-4b7a-9be1-f7b5420f9b21)

## Expected result

setting column visible places it on last place among selected

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version: 4.10.1
* Chrome v114
* Operating System: Windows

**Comment by AlekseyManetov** [comment] 2023-07-10 14:42
Hi @Kernstall, coild you please create a [codesanbox](https://codesandbox.io/s/8crl7t?file=/Example.tsx) with this case, because i can't reproduce it in our codebase.

**Comment by AlekseyManetov** [comment] 2023-07-17 15:57
I close this issue. If you could reproduce it and provide some artifacts for us, please reopen it

**Closed by AlekseyManetov** 2023-07-17 15:57 UTC
Labels: bug
