### ISSUE TITLE
Main Menu: Improve 2nd level dropdown menu

### ISSUE THREAD

**Issue by DzmitryTrubchyk** [epam/UUI#2496] opened 2024-09-05 16:47 UTC
Update it with #2474 issue in a parallel

Apply this change for all themes
A bit details:

- Change bg color for darker
- Change bg color for dropdown to lighter
- Apply color for hover lighter than dropdown bg color
- Finalize design for Active state, from 2nd level dropdown (Design TBD): 
![image](https://github.com/user-attachments/assets/d2afa17b-cbb4-4fc1-bc83-bfa770a2ba0a)

- Check with tooltip color 
![image](https://github.com/user-attachments/assets/3f13c7a4-b797-48ae-8309-6c8656af7b07)

**Comment by AlekseyManetov** [comment] 2024-12-09 14:09
Duplicate of https://github.com/epam/UUI/issues/2614

**Closed by AlekseyManetov** 2024-12-09 14:09 UTC
Labels: improvement, Main Menu
