### ISSUE TITLE
[MainMenu] Displaying issues

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#1124] opened 2023-03-16 11:38 UTC
## Description

There are several issues, related to the `MainMenu` component. Some of them are related to its new implementation (with `AdaptivePanel` under the hood).

The CodeSandbox link is the same for all the cases below: https://codesandbox.io/s/uui-main-menu-issues-fhpmvq.

### Steps to Reproduce

1. Open the application
2. Click on the "Open modal window" button and check if the page scroll is visible
3. Close the modal window by clicking on the "Close modal window" button
4. Make the screen's width ≤ 436px
5. Click on the "Open modal window" button and check if the page scroll is visible

### Actual result

On step 2, the page scroll is visible and functional when the modal window is open.
On step 5, the page scroll is **not** visible when the modal window is open.

### Expected result

On the steps 2 and 5 the page scroll is **not** visible when the modal window is open.

### Notes

It seems the window's size, where the body gets the correct style, is different for different amount (and/or length) of the `MainMenu` children.

Also, when removing the `MainMenu` components, the page scroll is **not** visible when the modal window is open for any window's width, that's why I think that opening the modal window is related to this component.

### Steps to Reproduce

1. Open the application (the browser's DevTools should be opened)
2. In "Network" tab in the DevTools check "Disable cache" option
3. Start reducing the window's width
    1. Check how images in the examples are displayed while resizing the window
    2. Check the requests list in the "Network" tab (with "All" or "Img" filter)
4. Reduce the window's width to 591px ± 5px
    1. Check how images in the examples are displayed while resizing the window
    2. Check the requests list in the "Network" tab (with "All" or "Img" filter)
5. For any window's width, click on the "Open modal window" button
    1. Check how images in the examples are displayed at that moment
    2. Check the requests list in the "Network" tab (with "All" or "Img" filter)
6. In "Network" tab in the DevTools uncheck "Disable cache" option and/or close the DevTools
7. Repeat steps 3-5 paying attention to the same things, mentioned in the sub-steps

### Actual result

When the cache is disabled, changing the window's size leads to images' "blinking", because the images are requested again on each change. At some point (step 4), the requests are sent endlessly, and the images are always "blinking". Opening a modal window also forces the images to re-render and make the requests.
When the cache is enabled, the requests are not sent (or are sent, but the value is retrieved from the cache), and the "blinking" doesn't happen.

### Expected result

With or without cache, resizing and opening a modal window doesn't lead to images "blinking" (which actually means the components are not full re-rendered).

### Notes

I tried to wrap the rendering functions in `useCallback`, render the avatar component without the dropdown, use `useMemo` and `memo` for both cases (children are defined as `items` or passed as children to the `MainMenu`) - nothing helps to overcome this problem. It doesn't exist in version 4.6.3.

While it is unlikely, that users will disable cache, it seems it is a sign, that the implementation has flaws, that may be crucial for other cases (if, for example, the component performs side effects, which are more heavy, than the avatar and logo images requesting).

I can also see this:
![image](https://user-images.githubusercontent.com/10310491/225606520-ce37ba96-7fe1-4cd6-ab07-804864aee8de.png)
Seems related.

## Environment

* UUI version: 4.10.0, 4.10.1
* Browser name: Google Chrome v.110.0.5481.178
* Operating System: Windows 10 64-bit

**Comment by sliim35** [comment] 2023-03-23 14:18
> When opening a modal window, body doesn't get overflow: hidden style for some window's widths

We faced the same issue recently

I created a poc and found out that:
- it happens when you have a burger in your `MainMenu` and it is not in DOM
- `componentWillMount` of Burger [rewrites styles](https://github.com/epam/UUI/blob/main/uui-components/src/navigation/MainMenu/Burger/Burger.tsx#L70), you can just type and check `document.body.style.overflow = 'hidden'` in console or try to inline styles
- [this compute function](https://github.com/epam/UUI/blob/main/uui-components/src/layout/AdaptivePanel.tsx#L113) render burger in virtual dom (even you don't have a burger in DOM)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/26935057/227231337-3ead3f08-9eba-428b-845f-14bec8049b77.png">

ps if you pass menu items as prop items console shows error with key

**Comment by AlekseyManetov** [comment] 2023-03-28 14:06
@vasilii-kovalev @sliim35  the first case of this issue was fixed in 4.10.2 version

**Comment by AlekseyManetov** [comment] 2023-08-22 11:10
> I can also see this:
![image](https://github.com/epam/UUI/assets/14283670/af67849b-8bb8-41b2-a89a-cc24371919e7)
Seems related.
Hi @vasilii-kovalev, sorry for the such long delay with answer. You are right, this warnings is related to the root course of this your first case. Because on every resize event we are rendering full array of items to measure if they fit container width, and then render only that elements which fits, that follows items order change, so it's required to have unique 'key' for each item.
I've fixed you codesandbox by adding keys and now images not blinking with disabled cache - https://codesandbox.io/s/uui-main-menu-issues-forked-lrr83f?file=/index.tsx:1926-1964

**Closed by AlekseyManetov** 2023-08-22 11:10 UTC
Labels: bug

**Comment by vasilii-kovalev** [comment] 2023-08-23 14:12
> > I can also see this:
> > ![image](https://user-images.githubusercontent.com/14283670/262330827-af67849b-8bb8-41b2-a89a-cc24371919e7.png)
> > Seems related.
> 
> Hi @vasilii-kovalev, sorry for the such a long delay with answer. You are right, this warnings are related to the root cause of your first case. Because on every resize event we are rendering full array of items to measure if they fit container width, and then render only that elements which fits, that follows items order change, so it's required to have unique 'key' for each item. I've fixed you codesandbox by adding keys and now images not blinking with disabled cache - https://codesandbox.io/s/uui-main-menu-issues-forked-lrr83f?file=/index.tsx:1926-1964

Thank you! I confirm, that there is no warning now, but when resizing the window to the 591px ± 5px (p. 4 in the original message), the component still forces children to re-render without stopping, even in your example with added `key`-s.

**Comment by AlekseyManetov** [comment] 2023-08-24 11:44
The issue here is due to the image blinking caused by disabled caching. When the items are being measured, the image starts with a width of zero. However, once it's loaded, its actual width is applied. This triggers a resize event that initiates re-rendering, leading to a loop.
For the main menu items to function properly, it's crucial that their width remains constant during rendering. Unfortunately, there's not much we can do to alter this behavior. If you deactivate disabled caching, this loop will likely cease.
